# Generated by Django 2.0.10 on 2019-02-08 11:26

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=15)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=15)),
                ('crop', models.CharField(choices=[('AKKER', 'Akkerbouw'), ('BOL', 'Bollenteelt'), ('GROENTE', 'Groenteteelt')], default='None', max_length=100)),
                ('startdate', models.DateField(default=datetime.date(2019, 2, 8))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2019, 2, 8))),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Plot')),
            ],
        ),
    ]
