# Generated by Django 2.0.10 on 2019-02-08 12:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='lon',
        ),
        migrations.AddField(
            model_name='plot',
            name='shape',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
