# Generated by Django 2.0.10 on 2019-02-08 14:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190208_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='location',
        ),
        migrations.AlterField(
            model_name='plot',
            name='shape',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
