# Generated by Django 2.1.7 on 2019-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_logbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
