# Generated by Django 2.1.7 on 2019-05-13 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20190409_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='time',
            field=models.TimeField(default=datetime.time(2, 0)),
        ),
        migrations.AlterField(
            model_name='plot',
            name='startdate',
            field=models.DateField(default=datetime.date(2019, 5, 13)),
        ),
        migrations.AlterField(
            model_name='scan',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 13)),
        ),
    ]
