# Generated by Django 2.1.7 on 2019-05-23 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20190520_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='flight_altitude',
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='plot',
            name='startdate',
            field=models.DateField(default=datetime.date(2019, 5, 23)),
        ),
        migrations.AlterField(
            model_name='scan',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 23)),
        ),
    ]
