# Generated by Django 2.1.7 on 2019-05-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20190531_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='shape',
            new_name='plot_shape',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='number',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='street',
        ),
        migrations.AddField(
            model_name='plot',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plot',
            name='crop_type',
            field=models.CharField(choices=[('BROCCOLI', 'Broccoli'), ('BLOEMKOOL', 'Bloemkool'), ('TULP', 'Tulpen'), ('LELY', 'Lelies'), ('CICHOREI', 'Cichorei'), ('AARDAPPEL', 'Aardappelen'), ('SPRUIT', 'Spruiten'), ('SLA', 'Sla')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='plot',
            name='startdate',
            field=models.DateField(default='2019-05-01'),
        ),
    ]
