# Generated by Django 2.1.7 on 2019-05-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20190531_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
