# Generated by Django 2.1.7 on 2019-05-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20190531_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='parent_plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Parent_Plot'),
        ),
    ]
