# Generated by Django 2.1.7 on 2019-05-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20190531_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='name',
        ),
    ]
