# Generated by Django 2.1.7 on 2019-05-31 11:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20190531_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('crop', models.CharField(choices=[('BROCCOLI', 'Broccoli'), ('BLOEMKOOL', 'Bloemkool'), ('TULP', 'Tulpen'), ('LELY', 'Lelies'), ('CICHOREI', 'Cichorei'), ('AARDAPPEL', 'Aardappelen'), ('SPRUIT', 'Spruiten'), ('SLA', 'Sla')], max_length=25, null=True)),
                ('season', models.CharField(choices=[('SPRING', 'Voorjaar'), ('SUMMER', 'Zomer'), ('FALL', 'Herfst'), ('WINTER', 'Winter')], max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('no_of_plants', models.PositiveIntegerField(null=True)),
                ('plant_date', models.DateField(null=True)),
                ('harvest_date_projected', models.DateField(null=True)),
                ('harvest_date_actual', models.DateField(null=True)),
                ('harvest_date_modelled', models.DateField(null=True)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Breed')),
            ],
        ),
        migrations.RenameField(
            model_name='plot',
            old_name='crop_type',
            new_name='crop',
        ),
        migrations.RenameField(
            model_name='plot',
            old_name='plot_shape',
            new_name='shape',
        ),
        migrations.AddField(
            model_name='planting',
            name='plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Plot'),
        ),
        migrations.AddField(
            model_name='plant',
            name='planting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Planting'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Plant'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Scan'),
        ),
    ]
