# Generated by Django 2.1.7 on 2019-06-08 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20190531_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='no_imgs',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='ortho',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='preprocess',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='quality',
            field=models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', max_length=10),
        ),
        migrations.AddField(
            model_name='scan',
            name='sensor',
            field=models.CharField(default='FC6310S', max_length=100),
        ),
        migrations.AddField(
            model_name='scan',
            name='tiles',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='upload',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='startdate',
            field=models.DateField(default=datetime.date(2019, 6, 8)),
        ),
        migrations.AlterField(
            model_name='scan',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 8)),
        ),
    ]
