# Generated by Django 2.1.7 on 2019-06-19 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_auto_20190617_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapnote',
            name='name',
            field=models.CharField(default='unkown', max_length=100),
        ),
        migrations.AlterField(
            model_name='plot',
            name='startdate',
            field=models.DateField(default=datetime.date(2019, 6, 19)),
        ),
        migrations.AlterField(
            model_name='scan',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 19)),
        ),
    ]
