# Generated by Django 2.1.7 on 2019-06-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_auto_20190619_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapnote',
            name='latlon',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='mapnote',
            name='scan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.Scan'),
            preserve_default=False,
        ),
    ]
