# Generated by Django 2.1.7 on 2019-06-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_auto_20190619_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapnote',
            old_name='latlon',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='mapnote',
            name='lon',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
