# Generated by Django 2.1.7 on 2019-06-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_auto_20190619_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='seen_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
