# Generated by Django 2.1.7 on 2019-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_auto_20190620_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='seen_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
