# Generated by Django 2.1.7 on 2019-06-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_auto_20190620_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='seen_by_user',
        ),
    ]
