# Generated by Django 2.1.7 on 2019-06-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_remove_scan_seen_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='seen_by_user',
            field=models.BooleanField(default=True),
        ),
    ]
