# Generated by Django 2.1.7 on 2019-06-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_scan_seen_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='seen_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
