# Generated by Django 2.1.7 on 2019-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_auto_20190620_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='no_imgs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='ortho',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='preprocess',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='tiles',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
